services:
  flight-controller:
    image: n1ckaleks/damn-vulnerable-drone-flight-controller:latest
    container_name: flight-controller
    privileged: true
    build:
      context: .
      dockerfile: ./flight-controller/Dockerfile
    volumes:
      - serial-uart-socket:/sockets
    networks:
      simulator:
        ipv4_address: 10.13.0.2

  companion-computer:
    image: n1ckaleks/damn-vulnerable-drone-companion-computer:latest
    container_name: companion-computer
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: ./companion-computer/Dockerfile
    depends_on:
      - flight-controller
    volumes:
      - serial-uart-socket:/sockets
    environment:
      - WIFI_ENABLED
    networks:
      simulator:
        ipv4_address: 10.13.0.3

  ground-control-station:
    image: n1ckaleks/damn-vulnerable-drone-ground-control-station:latest
    container_name: ground-control-station
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp
      - XAUTHORITY=/home/gcs/.Xauthority
      - HEADLESS=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/home/gcs/.Xauthority:ro
      - /etc/machine-id:/etc/machine-id:ro
    devices:
      - /dev/dri:/dev/dri
    build:
      context: .
      dockerfile: ./ground-control-station/Dockerfile
    depends_on:
      - companion-computer
    networks:
      simulator:
        ipv4_address: 10.13.0.4

  simulator:
    image: n1ckaleks/damn-vulnerable-drone-simulator:latest
    container_name: simulator
    privileged: true
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
    build:
      context: .
      dockerfile: ./simulator/Dockerfile
    ports:
      - "8080:8080" # gzweb
      - "8000:8000" # simulator mgmt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./simulator/mgmt:/Simulator/mgmt
    environment:
      - WIFI_ENABLED
    networks:
      simulator:
        ipv4_address: 10.13.0.5

volumes:
  serial-uart-socket:
  ardupilot:

networks:
  simulator:
    name: simulator
    internal: false
    driver: bridge
    ipam:
      config:
        - subnet: "10.13.0.0/24"
